_wandb:
    value:
        cli_version: 0.22.3
        e:
            mi9kucfxfcrdgoxua8vih1w8lufco729:
                codePath: test_training.py
                codePathLocal: test_training.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1999227580416"
                        used: "1806994579456"
                email: pj.skirmish@gmail.com
                executable: C:\Users\antoi\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 84419be383264d3854574f40dc486d8b0cd2230a
                    remote: https://github.com/SPhoenix-00/eigen2.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-13745f17-fa09-820c-3ec0-9f4eda3c2b25
                host: Bruh
                memory:
                    total: "68447875072"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\antoi\Documents\GitHub\eigen2\test_training.py
                python: CPython 3.13.1
                root: c:\Users\antoi\Documents\GitHub\eigen2
                startedAt: "2025-11-07T06:36:55.923149Z"
                writerId: mi9kucfxfcrdgoxua8vih1w8lufco729
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.13.1
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
actor_lr:
    value: 0.0001
batch_size:
    value: 4
buffer_size:
    value: 14000
critic_lr:
    value: 0.0003
loss_penalty_multiplier:
    value: 1
max_holding_period:
    value: 20
num_generations:
    value: 2
num_stocks:
    value: 108
population_size:
    value: 4
trading_period_days:
    value: 50
